version: '3'

services:

## MySQL
  mysqldb:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      #- ./mysql/data:/var/lib/mysql
      - ./mysql/data57:/var/lib/mysql      
      